### PR TITLE
Move host to class method.

### PR DESCRIPTION
**Pull request by tpendragon**
Need this in order to have a single point of entry for override in
ActiveFedora's cleanup method.

### CODE REVIEW

**Comment by jcoyne** [comment]
This looks great.  Any idea why the CI is suddenly failing?

**Comment by tpendragon** [comment]
@jcoyne: Yeah, needed LDP updated and Fedora Alpha 6 for everything to pass. Force pushed, next run should work.

**Comment by tpendragon** [comment]
Sigh. Rspec 3.

**Comment by jcoyne** [comment]
Just peg to rspec 2.99 and we should be good to go.

**Comment by tpendragon** [comment]
Done.

**Pull request merged**
